package com.shikidroid.ui

internal const val SHIKIDROID_TITLE = "Shikidroid"

internal const val INTERNET_CONNECTION_OFF_TEXT = "Нет интернет соединения"
internal const val INTERNET_CONNECTION_ON_TEXT = "Соединение восстановлено"

internal const val ENTER_TITLE = "Войти"
internal const val CONTINUE_TITLE = "Продолжить"
internal const val ENTER_LIKE_GUEST_TITLE = "Продолжить как Гость"
internal const val ONE_MORE_TRY_TITLE = "Повторить запрос"
internal const val GO_BACK_TITLE = "Вернуться назад"
internal const val EXIT_TITLE = "Выйти"

internal const val REQUEST_ERROR_TITLE = "Ошибка загрузки данных"

internal const val ANIME_TITLE = "Аниме"
internal const val MANGA_TITLE = "Манга"
internal const val RANOBE_TITLE = "Ранобэ"

internal const val EDIT_TEXT = "Редактировать"
internal const val IN_LIST_TEXT = "В список"
internal const val WATCH_TEXT = "Смотреть"

internal const val NOT_YET_RELEASED_TEXT = "Ещё не вышло"
internal const val ALL_WATCHED = "Просмотрено"
internal const val ALL_READED = "Прочитано"

internal const val TYPE_TEXT = "тип"
internal const val AGE_TEXT = "возраст"
internal const val RELEASE_DATE_TEXT = "дата выхода"
internal const val EPISODES_TEXT = "эпизоды"
internal const val EPISODE_TIME_TEXT = "время эп."
internal const val CHAPTERS_TEXT = "главы"
internal const val VOLUMES_TEXT = "тома"
internal const val STUDIO_TEXT = "студия"

internal const val WEB_VERSION_TITLE = "Веб-версия"
internal const val STATISTIC_TITLE = "Статистика"
internal const val LINKS_TITLE = "Ссылки"
internal const val SHARE_TITLE = "Поделиться"
internal const val CREATORS_TITLE = "Создатели"
internal const val STUDIOS_TITLE = "Студии"
internal const val DESCRIPTION_TITLE = "Описание"
internal const val ADDITIONAL_INFO_TITLE = "Дополнительная информация"
internal const val RELATED_TITLE = "Связанное"
internal const val CHARACTERS_TITLE = "Персонажи"
internal const val MAIN_CHARACTERS_TITLE = "Главные персонажи"
internal const val SUPPORTED_CHARACTERS_TITLE = "Второстепенные персонажи"
internal const val SCREENSHOTS_TITLE = "Кадры"
internal const val VIDEO_TITLE = "Видео"
internal const val SIMILAR_TITLE = "Похожее"
internal const val COMMENTS_TITLE = "Комментарии"
internal const val GRADE_TITLE = "Оценки"
internal const val LIST_TITLE = "Списки"
internal const val RELEASED_DATE_TITLE = "Время выхода"
internal const val FILTERS_TITLE = "Фильтры"
internal const val GENRE_TITLE = "Жанры"
internal const val AIRED_STATUS_TITLE = "Статус"
internal const val TYPE_TITLE = "Тип"
internal const val DURATION_TITLE = "Длительность"
internal const val AGE_RATING_TITLE = "Возрастной рейтинг"
internal const val YEAR_TITLE = "Год"
internal const val YEAR_RELEASED_TITLE = "Год выхода"
internal const val YEAR_SEASON_TITLE = "Год сезона"
internal const val SEASON_TITLE = "Сезон"

internal const val RELEASED_TITLE = "Вышедшее"

internal const val ORIGINAL_TITLE = "Оригинал"
internal const val SUBTITLES_TITLE = "Субтитры"
internal const val DUB_TITLE = "Озвучка"

internal const val INPUT_CHARACTER_NAME_TEXT = "Введите имя персонажа..."
internal const val CHARACTER_NOT_FOUND_TEXT = "Персонаж не найден"
internal const val DOWNLOAD_YET_ONE = "Загрузить ещё"

internal const val APPLY_BUTTON_TITLE = "Применить"
internal const val CLEAR_BUTTON_TITLE = "Сбросить"

internal const val EMPTY_SEARCH_TITLE = "Ничего не найдено"
internal const val EMPTY_LIST_TITLE = "Ваш список пуст"
internal const val EMPTY_EPISODE_TITLE = "В архиве нет нужного типа трансляции или эпизод ещё не вышел"
internal const val ENTER_CHARACTER_NAME = "Введите имя персонажа"

internal const val SEYU_TITLE = "Сэйю"
internal const val ROLES_ANIME_MANGA_TITLE = "Роли в аниме и манге"
internal const val BEST_ROLES_TITLE = "Лучшие роли"
internal const val BEST_WORKS_TITLE = "Лучшие работы"

internal const val INPUT_TITLE_TEXT = "Введите название"
internal const val INPUT_MIN_THREE_SYMBOLS = "Введите минимум три символа"

internal const val UPDATED_TEXT = "Обновлено"
internal const val DELETED_TEXT = "Удалено"
internal const val LISTS_UPDATED_TEXT = "Списки обновлены"
internal const val ALREADY_IN_LIST_TEXT = "Уже в списке"
internal const val DATA_UPDATE_ERROR_TEXT = "Не удалось обновить данные. Попробуйте ещё раз"
internal const val TRY_ANOTHER_ONE_ERROR_TEXT = "Произошла ошибка. Попробуйте ещё раз"
internal const val ALL_DATA_LOADED_TEXT = "Все данные загружены"
internal const val PLUS_ONE_EPISODE_TEXT = "Добавлен 1 эпизод к просмотренным"